services:
  zookeeper:
    image: "confluentinc/cp-zookeeper:7.5.4"
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      
  broker:
    image: "confluentinc/cp-kafka:7.5.4"
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
      - '29094:29094'
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: LISTENER1://broker:29092, LISTENER2://broker:9092, LISTENER3://broker:29094
      KAFKA_ADVERTISED_LISTENERS: LISTENER1://broker:29092, LISTENER2://localhost:9092, LISTENER3://192.168.50.2:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER1:PLAINTEXT, LISTENER2:PLAINTEXT, LISTENER3:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100

  kafkacat:
    image: confluentinc/cp-kafkacat
    command: sleep infinity
