(part "BME690"
    (packageRef "BME690")
    (interface
        (port "1" (symbPinId 1) (portName "GND_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "CSB") (portType INOUT))
        (port "3" (symbPinId 3) (portName "SDI") (portType INOUT))
        (port "4" (symbPinId 4) (portName "SCK") (portType INOUT))
        (port "5" (symbPinId 5) (portName "SDO") (portType INOUT))
        (port "6" (symbPinId 6) (portName "VDDIO") (portType INOUT))
        (port "7" (symbPinId 7) (portName "GND_2") (portType INOUT))
        (port "8" (symbPinId 8) (portName "VDD") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "262-BME690")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Bosch-Sensortec/BME690?qs=%252BXxaIXUDbq38jwlEAGDF7A%3D%3D")
    (property "Manufacturer_Name" "BOSCH")
    (property "Manufacturer_Part_Number" "BME690")
    (property "Description" "Multiple Function Sensor Modules BME690 is the gas sensor with Artificial Intelligence (AI) and integrated high-linearity and high-accuracy  pressure, humidity and temperature sensors.")
    (property "Datasheet_Link" "https://www.bosch-sensortec.com/products/environmental-sensors/gas-sensors/bme690/#documents")
    (property "symbolName1" "BME690")
)
